package com.maydaymemory.mae.basic;

/**
 * Represents a skeletal pose at a specific moment in time.
 * <p>
 * A {@code Pose} contains the local-space transforms (translation, rotation, scale)
 * of bones that define the current state of a skeleton during animation.
 * It does <b>not</b> include any information about the skeletal hierarchy
 * (e.g., parent-child bone relationships).
 * </p>
 * <p>
 * The list of bone transforms is typically ordered by ascending bone index to
 * enable efficient merging and blending of poses.
 * </p>
 */
public interface Pose {

    /**
     * Returns an iterable over the local transforms of bones in this pose.
     * The iteration order must be in ascending order of {@code boneIndex}.
     * <p>
     * Each transform corresponds to a bone in local space.
     * This iterable may include only a subset of bones if the pose is sparse (e.g., pose generated by partial animations).
     * </p>
     *
     * @return An {@code Iterable} of {@link BoneTransform} in sorted order by bone index.
     */
    Iterable<BoneTransform> getBoneTransforms();
}
